In [1]:
import numpy as np
import matplotlib.pyplot as pd
import pandas as pd

In [4]:
dataset=pd.read_csv('Social_Network_Ads.csv')

In [5]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [6]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [7]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [9]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [11]:
independent=dataset[["Age","EstimatedSalary","Gender_Male"]]
dependent=dataset["Purchased"]

In [12]:
independent.shape

(400, 3)

In [13]:
dependent

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [15]:
from sklearn.svm import SVC
classifier= SVC(kernel='rbf',random_state=0)
classifier=classifier.fit(x_train,y_train)

In [16]:
y_pred = classifier.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [19]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_pred)

In [20]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.76      0.96      0.85        85
           1       0.88      0.47      0.61        49

    accuracy                           0.78       134
   macro avg       0.82      0.72      0.73       134
weighted avg       0.81      0.78      0.76       134

In [21]:
print(cm)

[[82  3]
 [26 23]]